# Generated by Django 3.0.7 on 2021-02-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='curso_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='Institución_text',
        ),
    ]
