# Generated by Django 3.0.7 on 2021-02-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210201_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Institución_text',
            new_name='question_text',
        ),
    ]
